---
- name: Playbook para interactuar con Vault
  hosts: localhost
  tasks:
    - name: Ejecutar comando para obtener secreto desde Vault
      ansible.builtin.shell: |
        echo "los comandos funcionan, parece ser"
      register: vault_command_output

    - name: Mostrar salida del comando ejecutado
      ansible.builtin.debug:
        var: vault_command_output.stdout
