---
- name: Playbook para interactuar con Vault
  hosts: localhost
  tasks:
    - name: Ejecutar comando para obtener secreto desde Vault
      ansible.builtin.shell: |
        pwd
#        export VAULT_ADDR="http://48.217.48.214:31200"
#        export VAULT_TOKEN="hvs.mdJ8aEAsJPCiserJNBCtgc56"
#        vault kv get -format=json -mount="kv" "awx"
      register: vault_command_output

    - name: Mostrar salida del comando ejecutado
      ansible.builtin.debug:
        var: vault_command_output
