---
- name: Playbook para interactuar con Vault
  hosts: localhost
  tasks:
    - name: Ejecutar comando para obtener secreto desde Vault
      ansible.builtin.debug:
        msg: "La ejecución funciona correctamente"