---
- name: Playbook para interactuar con Vault
  hosts: localhost
  tasks:
    - name: Ejecutar comando para obtener secreto desde Vault
      ansible.builtin.shell: |
        vault kv get -format=json -mount="kv" "awx"
      register: vault_command_output

    - name: Parsear salida JSON de Vault
      ansible.builtin.set_fact:
        vault_data: "{{ vault_command_output.stdout | from_json | json_query('data.data') }}"

    - name: Mostrar claves y valores
      ansible.builtin.debug:
        msg: "{{ item.key }}: {{ item.value }}"
      with_dict: "{{ vault_data }}"
