---
- name: Print Vault Secret
  hosts: localhost
  tasks:
    - name: Look up secret from Vault
      ansible.builtin.debug:
        msg: >
          Secreto recuperado: 
          {{ lookup('hashi_vault', 'kv/awx secret=secret-formula') }}