---
- name: Print Vault Secret
  hosts: localhost
  tasks:
    - name: Look up secret from Vault
      ansible.builtin.debug:
        msg: >
          Secret: "{{lookup('hashi_vault', '/v1/kv/data/awx url=http://48.217.48.214:31200')}}"